[package]
name = "dungeon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
# tui = "0.19.0"
crossterm = "0.27.0"
ratatui = "0.26.0"
lazy_static = "1.4.0"
log = "0.4.21"
